version: "2.0"
services: 
    postgresdb:
        image: postgres:12
        restart: always
        environment: 
            - POSTGRES_PASSWORD=my-secret-pw
            - POSTGRES_DB=cdcr
        ports: 
            - 5432:5432
        volumes:
            - ./postgres-data:/var/lib/postgresql/data

    adminer:
        image: adminer
        restart: always
        ports:
            - 8080:8080

    redis:
        image: redis
        restart: always
        ports:
            - 6379:6379

    web:
        build: '.'
        ports:
            - 8001:80
        #links:
        #    - postgresdb
        environment: 
            SQLALCHEMY_DB_URI: "postgresql+psycopg2://postgres:my-secret-pw@192.168.0.31:5432/cdcr"
            SECRET: "topsecret123"