"""Add password salt for users

Revision ID: 20721bb6a953
Revises: fb5d592383f6
Create Date: 2020-04-17 14:38:35.345887

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '20721bb6a953'
down_revision = 'fb5d592383f6'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('salt', sa.String(length=64), nullable=True))
    op.create_unique_constraint(None, 'users', ['username'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'users', type_='unique')
    op.drop_column('users', 'salt')
    # ### end Alembic commands ###
