"""add admin perm to user table

Revision ID: 364df0607448
Revises: ee4b2e1be395
Create Date: 2020-05-01 09:04:59.075603

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '364df0607448'
down_revision = 'ee4b2e1be395'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('is_admin', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'is_admin')
    # ### end Alembic commands ###
