"""drop news text url, sci text, url in favour of relationship lookup

Revision ID: 5bbbd88f7acf
Revises: 7ddae5807eae
Create Date: 2020-05-09 11:07:26.182445

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5bbbd88f7acf'
down_revision = '7ddae5807eae'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('tasks', 'sci_text')
    op.drop_column('tasks', 'news_url')
    op.drop_column('tasks', 'news_text')
    op.drop_column('tasks', 'sci_url')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('tasks', sa.Column('sci_url', sa.VARCHAR(length=150), autoincrement=False, nullable=True))
    op.add_column('tasks', sa.Column('news_text', sa.TEXT(), autoincrement=False, nullable=True))
    op.add_column('tasks', sa.Column('news_url', sa.VARCHAR(length=255), autoincrement=False, nullable=True))
    op.add_column('tasks', sa.Column('sci_text', sa.TEXT(), autoincrement=False, nullable=True))
    # ### end Alembic commands ###
