"""Make pw max length longer

Revision ID: 86ebe258e29f
Revises: 20721bb6a953
Create Date: 2020-04-17 14:44:23.841340

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '86ebe258e29f'
down_revision = '20721bb6a953'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column("users", "password", type_=sa.String(255))
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column("users", "password", type_=sa.String(64))
    # ### end Alembic commands ###
