"""Add IAA priority column

Revision ID: 921f9c6e9456
Revises: ce6533e84e25
Create Date: 2020-05-08 11:39:23.837622

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '921f9c6e9456'
down_revision = 'ce6533e84e25'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('tasks', sa.Column('is_iaa_priority', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('tasks', 'is_iaa_priority')
    # ### end Alembic commands ###
