"""Add bad task qol improvements

Revision ID: ada801bded08
Revises: 97cd96bf17cb
Create Date: 2020-06-07 08:07:08.518200

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ada801bded08'
down_revision = '97cd96bf17cb'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('tasks', sa.Column('is_bad_reason', sa.String(length=255), nullable=True))
    op.add_column('tasks', sa.Column('is_bad_reported_at', sa.DateTime(), nullable=True))
    op.add_column('tasks', sa.Column('is_bad_user_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'tasks', 'users', ['is_bad_user_id'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'tasks', type_='foreignkey')
    op.drop_column('tasks', 'is_bad_user_id')
    op.drop_column('tasks', 'is_bad_reported_at')
    op.drop_column('tasks', 'is_bad_reason')
    # ### end Alembic commands ###
