"""add permission to view google sheets

Revision ID: ee4b2e1be395
Revises: 86ebe258e29f
Create Date: 2020-04-18 08:43:12.431652

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ee4b2e1be395'
down_revision = '86ebe258e29f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('view_gsheets', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'view_gsheets')
    # ### end Alembic commands ###
