"""make add similarity column for tasks

Revision ID: fb5d592383f6
Revises: f6161e41ef02
Create Date: 2020-04-17 10:48:12.596436

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'fb5d592383f6'
down_revision = 'f6161e41ef02'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('tasks', sa.Column('similarity', sa.Float(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('tasks', 'similarity')
    # ### end Alembic commands ###
